Iter1
jbakhtin/driving-school-route-coverage pull request #1
Opened 2023-04-19 07:02 UTC by jbakhtin

2023-04-20 10:35 UTC, mr-fard4y commented on cmd/routecoverage/main.go
> +	"context"
импорты

2023-04-20 10:35 UTC, mr-fard4y commented on README.md
> +![DB Structure](docs/images/db-structure.drawio.png)
1) нет описания таблиц - кртакое описание, назначение и структура
2) для всех таблиц, кроме users нужно поле description, описывающее доп.инфу про запись

2023-04-20 10:35 UTC, mr-fard4y commented on internal/server/server.go
> +	authHandler, err := auth.NewHandler(*s.config)
для чего здесь 5 "одинаковых" хэндлеров?

в рамках пакета описать один, и лоигку взаимодействия разбить по файлам, НО не отдельным пакетам

2023-04-20 10:35 UTC, mr-fard4y commented on internal/storages/sqlstorage/entities/area/area.go
> +type Storage struct {
для чего каждая модель данных содержит свою структуру Storage?

2023-04-20 10:35 UTC, mr-fard4y commented on internal/storages/sqlstorage/migrations/20230417223555_create_users_table.sql
> +                      login text NOT NULL UNIQUE,
логин и иные приватные данные должны храниться в шифрованном виде, а не обычном тексте

[pgcrypto](https://www.postgresql.org/docs/12/pgcrypto.html#id-1.11.7.34.6)

2023-04-20 10:35 UTC, mr-fard4y commented on internal/storages/sqlstorage/migrations/20230417223555_create_users_table.sql
> +                      created_at text NOT NULL,
время хранится в таймстампах или нужной типе времени

[datetime](https://postgrespro.ru/docs/postgresql/9.4/datatype-datetime)

2023-04-20 10:35 UTC, mr-fard4y commented on README.md
> +![DB Structure](docs/images/db-structure.drawio.png)
перерисовать, чтобы количество линий и их расположение было более читабельным:
1 колонца - Users
2 колонка - Routes, Areas
3 колонка - Marks, Points

2023-04-20 10:35 UTC, mr-fard4y commented on README.md
> +![DB Structure](docs/images/db-structure.drawio.png)
при необходимости хранения активности пользователя, Users можно разделить на 2 таблицы:
1) общая информация о пользователе - имя, почта, etc
2) авторизационная информация о пользователей - логин, пароль, временные-метки активности

2023-04-20 10:35 UTC, mr-fard4y commented on README.md
> +### Инкремент 2
нет фоновых задач и задач с конкурентностью/многопоточностью

2023-04-20 10:35 UTC, mr-fard4y commented on README.md
> +![DB Structure](docs/images/db-structure.drawio.png)
для чего и почему все таблицы завязаны на пользователя?
продумать и упростить связи между таблицами

2023-04-27 11:03 UTC, jbakhtin commented on internal/storages/sqlstorage/migrations/20230417223555_create_users_table.sql
> +                      login text NOT NULL UNIQUE,
Они будут хэшироваться на уровне приложение, не на уровне sql

2023-04-27 11:07 UTC, jbakhtin commented on README.md
> +### Инкремент 2
В фоновом процессе будет отправка уведомлений, на данный момент пока что уведомления будут типа "подтвердить почту"
Других кейсов пока не придумал в рамках поставленной задачи

2023-04-27 15:24 UTC, jbakhtin commented on README.md
> +![DB Structure](docs/images/db-structure.drawio.png)
Упростил немного схему:
Например принадлежность маршрутов к заданной территории на карте будет определяться PostGIS на основе географических данных
Остальные же сущности это создаваемые пользователем объекты на карте, которые должны быть привязаны к нему

2023-04-27 15:25 UTC, jbakhtin commented on internal/storages/sqlstorage/migrations/20230417223555_create_users_table.sql
> +                      created_at text NOT NULL,
Да, мой косяк, проглядел, на дальнейших стадиях разработки всплыло бы

2023-05-31 21:00 UTC, tmvrus requested changes
Где тесты?

2023-06-08 14:23 UTC, tmvrus requested changes
Из заявленного сделаны только хендлеры для пользователя, такую работу я принять не могу

2023-06-09 14:28 UTC, closed without merging