Iter1 new
jbakhtin/driving-school-route-coverage pull request #2
Opened 2023-06-09 14:29 UTC by jbakhtin

2023-06-12 18:34 UTC, tmvrus requested changes
- у тебя индивидуальный проект, в нем лежат бинарный файлы из общего
- рекомендую еще раз ознакомиться с темой контекстов
- не следует игнорировать ошибки, их следует либо логировать либо пробрасывать в вызывающий код
- код которые не используется - засоряет проект и усложняет его чтение

2023-06-12 18:34 UTC, tmvrus commented on cmd/routecoverage/main.go
> +		fmt.Println(err)
fmt не рекомендуется использовать для логирования, это материал 3го спринта

2023-06-12 18:34 UTC, tmvrus commented on cmd/routecoverage/main.go
> +		logger.Error(err.Error())
тут какая-то странная ситуация: выглидят так что config.GetConfig() должен возвращать ошибку, но не возвращает. Какая тогда ошибка проверятся сразу после?

2023-06-12 18:34 UTC, tmvrus commented on cmd/routecoverage/main.go
> +			return
этот return лишен смысла, если его убрать, ничего не изменится

2023-06-12 18:34 UTC, tmvrus commented on cmd/routecoverage/main.go
> +	ctxOS, _ := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
рекомендую передать тут внешний контекст, поскольку он будет учитываться при обработке сигналов
рекомендую ознакомиться
https://pkg.go.dev/os/signal#NotifyContext

2023-06-12 18:34 UTC, tmvrus commented on cmd/routecoverage/main.go
> +		logger.Info(err.Error())
довольно странно логировать ошибку с уровнем Info

2023-06-12 18:34 UTC, tmvrus commented on cmd/routecoverage/main.go
> +	time.Sleep(2 * time.Second)
смысл этого кода понятен только автору, для меня это выглядит как костыль под неудачный дизайн остановки приложения

2023-06-12 18:34 UTC, tmvrus commented on internal/application/app.go
> +	authComposite, _ := api.NewAuthComposite(cfg)
не ясно почему тут игнорируется возвращаемая ошибка

2023-06-12 18:34 UTC, tmvrus commented on internal/application/app.go
> +		})
если нужен тестовый хендлер который напишет в браузер test, то лучше использовать writer.Write
если нужно логировать, то используй логгер

2023-06-12 18:34 UTC, tmvrus commented on internal/application/app.go
> +	err := s.ListenAndServe()
ListenAndServe всегда возвращает ошибку, рекомендую ознакомится с документацией и обрабатывать это корректно

2023-06-12 18:34 UTC, tmvrus commented on internal/application/apperror/error.go
> +	BadRequestParamsCode  = "003"
вот эти коды выглядят довольно странно, рекомендую еще раз ознакомиться с разделом errors курса

2023-06-12 18:34 UTC, tmvrus commented on internal/domain/repositories/user.go
> +}
в методы базы данных принято пробрасывать внешний контекст из запроса

2023-06-12 18:34 UTC, tmvrus commented on internal/domain/services/auth.go
> +		return nil
ошибку можно хотя бы логировать

2023-06-12 18:34 UTC, tmvrus commented on internal/domain/services/auth.go
> +		if strings.Contains(err.Error(), "sql: no rows in result set") {
errors.Is + sql.ErrNoRows

2023-06-12 18:34 UTC, tmvrus commented on internal/domain/services/auth.go
> +	hashedPassword := h.Sum(nil)
это довольно чувствительный код, лучше выделать его в отдельную ф-ю

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/handlers/area.go
> +//func (h *Handler) CreateArea() http.HandlerFunc {
в рабочем проекте не должно быть кода который закомментирован

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/handlers/auth.go
> +			if strings.Contains(err.Error(), "duplicate key value violates") {
errors.Is

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/handlers/mark.go
> +//func (h *Handler) CreateMark() http.HandlerFunc {
в рабочем проекте не должно быть кода который закомментирован

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/handlers/route.go
> +//func (h *Handler) CreateRoute() http.HandlerFunc {
в рабочем проекте не должно быть кода который закомментирован

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/middleware/validateLoginParams.go
> +		_ = json.Unmarshal(bodyBytes, &request)
игнорирование ошибки

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/middleware/validateLoginParams.go
> +		req.Body.Close() //  must close
игнорирование ошибки

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/api/middleware/validateRegistrationParams.go
> +		req := r.Clone(r.Context())
какой в этом смысл?

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/database/postgres/repository/user.go
> +	err := ur.QueryRow(query.CreateUser, &user.Name, &user.Lastname, &user.Login, &user.Email, &user.Password).
как обрабатывается случай когда пользователь уже есть?

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/database/postgres/repository/user.go
> +	err := ur.QueryRow(query.GetUserByID, id).
современный подход - использовать QueryRowContext вместо QueryRow

2023-06-12 18:34 UTC, tmvrus commented on internal/infrastructure/database/postgres/repository/user.go
> +}
тут печальная пустота

2023-06-12 18:34 UTC, tmvrus commented on internal/interfaces/services/auth.go
> +	LoginUser(request services.UserLoginRequest) (*services.UserLoginResponse, error)
не хватает контекста

2023-06-12 18:34 UTC, tmvrus commented on internal/utils/mailer/mailer.go
> +func NewMail(to string, subject string, body string) *Mail {
go позволяет указать тип один раз
```
func NewMail(to, subject, body string) *Mail
```

2023-06-12 18:34 UTC, tmvrus commented on internal/utils/mailer/mailer.go
> +		mails = make(chan Mail, 5)
смысл цифры 5 понятен только автору кода, если бы тут была именованная константа - было бы читабельней

2023-06-12 18:34 UTC, tmvrus commented on internal/utils/mailer/mailer.go
> +					fmt.Println(err)
log

2023-06-12 18:34 UTC, tmvrus commented on internal/utils/mailer/mailer.go
> +		fmt.Println(err)
log

2023-06-12 18:34 UTC, tmvrus commented on internal/utils/mailer/mailer.go
> +			return nil
если в канале mails останутся письма, то они никуда не отправятся, код к этому не готов

2023-06-12 18:34 UTC, tmvrus commented on internal/utils/ratelimiter/ratelimiter.go
> +package ratelimiter
весь этот код можно заменить одним каналом с нужной емкостью:
```go
limiter := make(chan struct{}, limit)
limiter <- struct{} // захватываем слот
// тут выполняется работа
<- limiter // освобождаем слот

```

2023-06-20 04:54 UTC, jbakhtin commented on cmd/routecoverage/main.go
> +		fmt.Println(err)
Поправил

2023-06-20 04:56 UTC, jbakhtin commented on cmd/routecoverage/main.go
> +		logger.Error(err.Error())
Поправил, добавил ошибку возвращаемую вторым значением

2023-06-29 13:40 UTC, jbakhtin commented on cmd/routecoverage/main.go
> +			return
Поправил

2023-06-29 13:44 UTC, jbakhtin commented on cmd/routecoverage/main.go
> +		logger.Info(err.Error())
Поправил

2023-06-29 13:47 UTC, jbakhtin commented on cmd/routecoverage/main.go
> +	ctxOS, _ := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
Переписал завершение программы. Реализовал пакет Closer который позволяет передать в него все функции завершения

2023-06-29 13:51 UTC, jbakhtin commented on cmd/routecoverage/main.go
> +	time.Sleep(2 * time.Second)
Переписал завершение программы. Перенес ожидание окончания функций завершения в пакет Сloser

2023-06-29 17:50 UTC, jbakhtin commented on internal/domain/services/auth.go
> +		return nil
да, странное решение, переписал - прокидываю ошибку ниже и логирую

2023-07-02 13:52 UTC, jbakhtin commented on internal/application/app.go
> +	authComposite, _ := api.NewAuthComposite(cfg)
Действительно, упустил. Добавил обработку ошибки

2023-07-02 14:23 UTC, jbakhtin commented on internal/application/app.go
> +	err := s.ListenAndServe()
Поправил

2023-07-02 14:49 UTC, jbakhtin commented on internal/application/apperror/error.go
> +	BadRequestParamsCode  = "003"
Это уникальные идентификаторы ошибок, по крайней мере я постарался это реализовать (Или хотя бы заложить такую возможность, поэкспериментировать с ней). Они предназначены для возврата клиенту, используещиму наше API. Например UserAlreadyExistsCode или BadRequestParamsCode будут возвращены со статусом http BadRequest 400, но благодаря идентификатору ошибки они смогут найти более подробную информацию о ней в документации к API.

2023-07-02 14:50 UTC, jbakhtin commented on internal/domain/services/auth.go
> +		if strings.Contains(err.Error(), "sql: no rows in result set") {
Поправил. Почему константы есть не для всех ошибок? Например я не могу найти константу для ошибки duplicate keys

2023-07-02 14:59 UTC, jbakhtin commented on internal/infrastructure/api/handlers/auth.go
> +			if strings.Contains(err.Error(), "duplicate key value violates") {
Переделал, пред сосзданием пользваотеля делаю дополнительный запрос к базе данных, на проверку налисчия  пользователя.

2023-07-02 15:27 UTC, jbakhtin commented on internal/infrastructure/api/middleware/validateLoginParams.go
> +		_ = json.Unmarshal(bodyBytes, &request)
поправил

2023-07-02 15:27 UTC, jbakhtin commented on internal/infrastructure/api/middleware/validateLoginParams.go
> +		req.Body.Close() //  must close
Поправил

2023-07-02 15:43 UTC, jbakhtin commented on internal/infrastructure/api/middleware/validateRegistrationParams.go
> +		req := r.Clone(r.Context())
Так как тело запроса можно прочитать только один раз, следовательно мне необходимо его скопировать, что бы произвести над ним некоторые действия в middleware, а потом исходный запрос передать для дальнейшей обработки в handler

2023-07-02 15:44 UTC, jbakhtin commented on internal/infrastructure/database/postgres/repository/user.go
> +	err := ur.QueryRow(query.CreateUser, &user.Name, &user.Lastname, &user.Login, &user.Email, &user.Password).
На уровне сервисного слоя я делаю обращение к базе данный и проверяю наличие пользователя с помощью метода getUserByLogin()

2023-07-02 15:45 UTC, jbakhtin commented on internal/infrastructure/database/postgres/repository/user.go
> +	err := ur.QueryRow(query.GetUserByID, id).
Поправил

2023-07-02 16:01 UTC, jbakhtin commented on internal/utils/mailer/mailer.go
> +func NewMail(to string, subject string, body string) *Mail {
Поправил

2023-07-02 16:20 UTC, jbakhtin commented on internal/utils/mailer/mailer.go
> +		mails = make(chan Mail, 5)
перенес в кофниг

2023-07-02 16:22 UTC, jbakhtin commented on internal/utils/mailer/mailer.go
> +			return nil
да, нужно будет доработать и сохранить письма перед завершением прогрммы

2023-07-25 21:48 UTC, tmvrus approved these changes

2023-07-26 06:50 UTC, jbakhtin commented
Merge iteration 1 to Main

2023-07-26 06:50 UTC, merged